plugins {
    id 'com.android.application'
}

android {
    namespace 'com.riebhopallibrary.app'
    compileSdk 36

    defaultConfig {
        applicationId 'com.riebhopallibrary.app'
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.webkit:webkit:1.17.0'
}
